name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    run-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.3, 8.2, 8.1]
                laravel: ["^11.0", "^10.0"]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                  - laravel: 10.*
                    testbench: 8.*
                  - laravel: 11.*
                    testbench: 9.* 
                exclude:
                  - laravel: 11.*
                    php: 8.1
                    
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, exif
                  coverage: none
